# Use an official Node runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /my-component-library

# Copy the package.json and package-lock.json
COPY package*.json .

# Install any needed packages specified in package.json
RUN npm install

# Copy the rest of your application's code
COPY . .

# Run npm build when the container launches
CMD ["npm", "run", "test"]
