name: Run tests then Deploy

on:
  push:
    branches: [ main ]  # Run this on pushes to the main branch
  pull_request:
    branches: [ main ]  # Also run on pull requests to the main branch
  workflow_dispatch:    # Allow manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'  # Keep the Node version consistent with Docker
          cache: 'npm'

      - run: npm test
