name: Run tests 
on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]  
  workflow_dispatch:    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'  
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

